### ISSUE TITLE
crash due to armormaterial already in use.

### ISSUE THREAD

**Issue by hazerddex** [Lance5057/Tinkers-Defense#133]
happens on start up
> ```
> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
>   HCASM (HammerCore-1.12.2-2.0.4.7.jar)
>   midnight (themidnight-0.3.5.jar)
>   AstralCore (astralsorcery-1.12.2-1.10.20.jar)
>   CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
>   ForgelinPlugin (Forgelin-1.8.3.jar)
>   Plugin (NotEnoughIDs-1.5.4.4.jar)
>   llibrary (llibrary-core-1.0.11-1.12.2.jar)
>   IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
>   LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
>   AALoadingPlugin (arcanearchives-0.2.0.6.jar)
>   PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
>   SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
>   IvToolkit (IvToolkit-1.3.3-1.12.jar)
>   DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
>   FarseekCoreMod (Farseek-1.12-2.3.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // Hi. I'm Minecraft, and I'm a crashaholic.
> 
> Time: 8/27/19 1:23 PM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Compendium (tinkerscompendium)
> Caused by: java.lang.IllegalArgumentException: Page type armormaterial already in use.
> 	at slimeknights.mantle.client.book.BookLoader.registerPageType(BookLoader.java:92)
> 	at lance5057.tDefense.core.library.book.CompendiumBook.init(CompendiumBook.java:26)
> 	at lance5057.tDefense.TinkersCompendium.preInit(TinkersCompendium.java:106)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> 	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 716418504 bytes (683 MB) / 2147483648 bytes (2048 MB) up to 7516192768 bytes (7168 MB)
> 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 141 mods loaded, 141 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State | ID                              | Version                  | Source                                               | Signature                                |
> 	|:----- |:------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
> 	| LCH   | minecraft                       | 1.12.2                   | minecraft.jar                                        | None                                     |
> 	| LCH   | mcp                             | 9.42                     | minecraft.jar                                        | None                                     |
> 	| LCH   | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCH   | forge                           | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCH   | ivtoolkit                       | 1.3.3-1.12               | minecraft.jar                                        | None                                     |
> 	| LCH   | dsurroundcore                   | 3.5.4.3                  | minecraft.jar                                        | None                                     |
> 	| LCH   | swordskillsapi                  | 1.1.0                    | 1.12.2-SwordSkillsApi-1.1.0.jar                      | None                                     |
> 	| LCH   | dynamicswordskills              | 1.12.2-6.0.1             | 1.12.2-DynamicSwordSkills-6.0.1.jar                  | None                                     |
> 	| LCH   | jei                             | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                            | None                                     |
> 	| LCH   | abyssalcraft                    | 1.9.9                    | AbyssalCraft-1.12.2-1.9.9.jar                        | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
> 	| LCH   | ctm                             | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
> 	| LCH   | roots                           | 1.12.2-3.0.7             | Roots-1.12.2-3.0.7.jar                               | None                                     |
> 	| LCH   | mysticalworld                   | 1.12.2-1.4.2             | MysticWorld-1.12.2-1.4.2.jar                         | None                                     |
> 	| LCH   | chisel                          | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
> 	| LCH   | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
> 	| LCH   | baubles                         | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
> 	| LCH   | thaumcraft                      | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                     | None                                     |
> 	| LCH   | twilightforest                  | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar          | None                                     |
> 	| LCH   | tconstruct                      | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                     | None                                     |
> 	| LCH   | acintegration                   | 1.8.1                    | AbyssalCraft+Integration-1.12.2-1.8.1.jar            | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
> 	| LCH   | orbis-lib                       | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build78.jar                   | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
> 	| LCH   | aether                          | 0.2.1                    | aether_ii-1.12.2-0.2.1+build78-universal.jar         | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
> 	| LCH   | biomesoplenty                   | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar        | None                                     |
> 	| LCH   | botania                         | r1.10-361                | Botania+r1.10-361.jar                                | None                                     |
> 	| LCH   | craftstudioapi                  | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar   | None                                     |
> 	| LCH   | natura                          | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                           | None                                     |
> 	| LCH   | harvestcraft                    | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
> 	| LCH   | animania                        | 1.6.2                    | animania-1.12.2-1.6.2.jar                            | None                                     |
> 	| LCH   | antiqueatlas                    | 4.5.1                    | antiqueatlas-1.12.2-4.5.1.jar                        | e631d7254e451d0360d0148cb21407d5511d45e9 |
> 	| LCH   | antiqueatlasoverlay             | 1.2                      | antiqueatlas-1.12.2-4.5.1.jar                        | e631d7254e451d0360d0148cb21407d5511d45e9 |
> 	| LCH   | ebwizardry                      | 4.2.1                    | ElectroblobsWizardry-4.2.1-MC1.12.2.jar              | None                                     |
> 	| LCH   | arcane_essentials               | 1.0                      | Arcane+Essentials-0.9.1.jar                          | None                                     |
> 	| LCH   | gbook_snapshot                  | 2.9.1.s5                 | Guidebook-1.12.2-2.9.1.s5.jar                        | None                                     |
> 	| LCH   | arcanearchives                  | 0.2.0.6                  | arcanearchives-0.2.0.6.jar                           | None                                     |
> 	| LCH   | conarm                          | 1.2.4                    | conarm-1.12.2-1.2.4.jar                              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
> 	| LCH   | armoryexpansion                 | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
> 	| LCH   | armoryexpansion-custommaterials | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
> 	| LCH   | llibrary                        | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
> 	| LCH   | iceandfire                      | 1.8.1                    | iceandfire-1.8.1.jar                                 | None                                     |
> 	| LCH   | armoryexpansion-iceandfire      | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
> 	| LCH   | armoryexpansion-matteroverdrive | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
> 	| LCH   | astikorcarts                    | 1.12.2-0.1.2.7           | astikorcarts-1.12.2-0.1.2.7.jar                      | None                                     |
> 	| LCH   | astralsorcery                   | 1.10.20                  | astralsorcery-1.12.2-1.10.20.jar                     | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
> 	| LCH   | atum                            | 2.0.10                   | Atum-1.12.2-2.0.10.jar                               | None                                     |
> 	| LCH   | betteranimalsplus               | 7.1.0                    | betteranimalsplus-1.12.2-7.1.0.jar                   | None                                     |
> 	| LCH   | guideapi                        | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                          | None                                     |
> 	| LCH   | bloodmagic                      | 1.12.2-2.4.1-103         | BloodMagic-1.12.2-2.4.1-103.jar                      | None                                     |
> 	| LCH   | bloodarsenal                    | 1.12.2-2.2.0-28          | BloodArsenal-1.12.2-2.2.0-28.jar                     | None                                     |
> 	| LCH   | bloodtinker                     | 1.0.5                    | bloodtinker-1.0.5.jar                                | None                                     |
> 	| LCH   | hammercore                      | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
> 	| LCH   | botanicadds                     | 3r                       | BotanicAdditions-1.12.2-3r.jar                       | None                                     |
> 	| LCH   | carryon                         | 1.12.1                   | CarryOn+MC1.12.2+v1.12.1.jar                         | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
> 	| LCH   | cavern                          | 2.2.0                    | Cavern_1.12.2-v2.2.0.jar                             | b78e30ad27c82f3e348f76edf497058678207299 |
> 	| LCH   | chameleon                       | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                             | None                                     |
> 	| LCH   | extendedrenderer                | v1.0                     | coroutil-1.12.1-1.2.31.jar                           | None                                     |
> 	| LCH   | coroutil                        | 1.12.1-1.2.31            | coroutil-1.12.1-1.2.31.jar                           | None                                     |
> 	| LCH   | configmod                       | v1.0                     | coroutil-1.12.1-1.2.31.jar                           | None                                     |
> 	| LCH   | desirepaths                     | 1.12.1-1.2.8             | desirepaths-1.12.1-1.2.8.jar                         | None                                     |
> 	| LCH   | dldungeonsjbg                   | 1.12.5                   | DoomlikeDungeons-1.12.5-MC1.12.2.jar                 | None                                     |
> 	| LCH   | dynamictrees                    | 1.12.2-0.9.5             | DynamicTrees-1.12.2-0.9.5.jar                        | None                                     |
> 	| LCH   | dynamictreesbop                 | 1.12.2-1.4.1e            | DynamicTreesBOP-1.12.2-1.4.1e.jar                    | None                                     |
> 	| LCH   | dynamictreesphc                 | 1.12.2-1.4.2             | DynamicTreesPHC-1.12.2-1.4.2.jar                     | None                                     |
> 	| LCH   | dynamictreestc                  | 1.12.2-1.4.1e            | DynamicTreesTC-1.12.2-1.4.1e.jar                     | None                                     |
> 	| LCH   | net.blacklab.lib                | 6.0.2.5                  | EBLib-6.0.2.5.jar                                    | None                                     |
> 	| LCH   | emberroot                       | 1.3.9                    | EmberRootZoo-1.12.2-1.3.10.jar                       | None                                     |
> 	| LCH   | mysticalmechanics               | 0.8-hotfix               | Mystical+Mechanics-0.8-hotfix.jar                    | None                                     |
> 	| LCH   | embers                          | 1.13-hotfix2             | EmbersRekindled-1.13-hotfix2.jar                     | None                                     |
> 	| LCH   | emberstic                       | 0.1.0                    | emberstic-0.1.0.jar                                  | None                                     |
> 	| LCH   | erebus                          | 1.0.30                   | Erebus-1.0.30.jar                                    | None                                     |
> 	| LCH   | farseek                         | 2.3.2                    | Farseek-1.12-2.3.2.jar                               | None                                     |
> 	| LCH   | forgelin                        | 1.8.3                    | Forgelin-1.8.3.jar                                   | None                                     |
> 	| LCH   | gasesframework                  | 2.0.0                    | gasesframework-1.12.2-2.0.0-pre1.jar                 | None                                     |
> 	| LCH   | gases                           | 2.0.0                    | gases-1.12.2-2.0.0-pre1.jar                          | None                                     |
> 	| LCH   | grapplemod                      | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                          | None                                     |
> 	| LCH   | grimoireofgaia                  | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar                   | None                                     |
> 	| LCH   | hw_inv                          | 1.12.1-1.1.9             | hostileworlds_invasions-1.12.1-1.1.9.jar             | None                                     |
> 	| LCH   | hungeringdarkness               | 1.2.1                    | Hungering+Darkness-1.12.2-1.2.1.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
> 	| LCH   | immersiveengineering            | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
> 	| LCH   | immersivetech                   | 1.3.10                   | immersivetech-1.12-1.3.10.jar                        | None                                     |
> 	| LCH   | improvableskills                | 3.6.3r                   | ImprovableSkills-1.12.2-3.6.3r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
> 	| LCH   | infernalmobs                    | 1.7.6                    | InfernalMobs-1.12.1.jar                              | None                                     |
> 	| LCH   | instantunify                    | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                        | None                                     |
> 	| LCH   | lex                             | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                               | None                                     |
> 	| LCH   | librarianlib                    | 4.19.2                   | librarianlib-1.12.2-4.19.2-release.jar               | None                                     |
> 	| LCH   | libraryex                       | 1.0.11                   | LibraryEx-1.12.2-1.0.11.jar                          | None                                     |
> 	| LCH   | lmreengaged                     | 8.0.1.66                 | LittleMaidReengaged-8.0.1.66-unofficial-1.12.2.jar   | None                                     |
> 	| LCH   | mystcraft                       | 0.13.7.03                | mystcraft-1.12.2-0.13.7.03.jar                       | None                                     |
> 	| LCH   | lootbags                        | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                          | None                                     |
> 	| LCH   | timecore                        | 1.0.0                    | TimeCore-1.12.2-1.0.0.jar                            | None                                     |
> 	| LCH   | lootgames                       | 1.0.1                    | LootGames-1.12.2-1.0.1-hotfix.jar                    | None                                     |
> 	| LCH   | lostcities                      | 2.0.20                   | lostcities-1.12-2.0.20.jar                           | None                                     |
> 	| LCH   | lostsouls                       | 1.1.4                    | lostsouls-1.12-1.1.4.jar                             | None                                     |
> 	| LCH   | lycanitesmobs                   | 2.0.0.4 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.0.4.jar                     | None                                     |
> 	| LCH   | mca                             | 6.0.0-beta               | MCA-1.12.2-6.0.0-beta-universal.jar                  | None                                     |
> 	| LCH   | metallurgy                      | 0.2.2                    | Metallurgy-4-Reforged-0.2.2.jar                      | None                                     |
> 	| LCH   | mininglantern                   | 1.0.0                    | MiningLantern-1.12.2-1.0.0.jar                       | None                                     |
> 	| LCH   | moartinkers                     | 0.6.0                    | moartinkers-0.6.0.jar                                | None                                     |
> 	| LCH   | moremystcraft                   | 0.8.4                    | moremystcraft-1.12.2-0.8.4.jar                       | None                                     |
> 	| LCH   | moveplus                        | 1.12.1-2.4.6             | moveplus-1.12.1-2.4.6.jar                            | None                                     |
> 	| LCH   | mowziesmobs                     | 1.5.4                    | mowziesmobs-1.5.4.jar                                | None                                     |
> 	| LCH   | multimob                        | 1.0.5                    | multimob-1.0.5.jar                                   | None                                     |
> 	| LCH   | naturescompass                  | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                      | None                                     |
> 	| LCH   | neat                            | 1.4-17                   | Neat+1.4-17.jar                                      | None                                     |
> 	| LCH   | netherex                        | 2.0.12                   | NetherEx-1.12.2-2.0.12.jar                           | None                                     |
> 	| LCH   | neid                            | 1.5.4.4                  | NotEnoughIDs-1.5.4.4.jar                             | None                                     |
> 	| LCH   | pages                           | 1.3.3                    | pages-1.12.2-1.3.3.jar                               | None                                     |
> 	| LCH   | patchouli                       | 1.0-19                   | Patchouli-1.0-19.jar                                 | None                                     |
> 	| LCH   | plustic                         | 7.0.7.0                  | plustic-7.0.7.0.jar                                  | None                                     |
> 	| LCH   | primitivemobs                   | 1.2.3a                   | primitivemobs-1.2.3a.jar                             | None                                     |
> 	| LCH   | reccomplex                      | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                         | None                                     |
> 	| LCH   | additionalstructures            | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar     | None                                     |
> 	| LCH   | ruins                           | 17.2                     | Ruins-1.12.2.jar                                     | None                                     |
> 	| LCH   | silentlib                       | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                      | None                                     |
> 	| LCH   | scalinghealth                   | 1.3.37                   | ScalingHealth-1.12.2-1.3.38+143.jar                  | None                                     |
> 	| LCH   | sereneseasons                   | 1.2.16                   | SereneSeasons-1.12.2-1.2.16-universal.jar            | None                                     |
> 	| LCH   | flammpfeil.slashblade           | mc1.12-r25               | SlashBlade-mc1.12-r25.jar                            | None                                     |
> 	| LCH   | slashbladetic                   | V1.0.8-MC1.12.2          | SlashBladeTic-V1.0.8-MC1.12.2.jar                    | None                                     |
> 	| LCH   | storagedrawers                  | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                      | None                                     |
> 	| LCH   | streams                         | 0.4.7                    | Streams-1.12-0.4.7.jar                               | None                                     |
> 	| LCH   | taiga                           | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                               | None                                     |
> 	| LCH   | tcinventoryscan                 | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar           | None                                     |
> 	| LCH   | thaumicperiphery                | 0.3.0                    | thaumicperiphery-0.3.0.jar                           | None                                     |
> 	| LCH   | beneath                         | 1.5.1                    | The+Beneath-1.12.2-1.5.1.jar                         | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
> 	| LCE   | tinkerscompendium               | 1.4.2.29.2               | tinkersdefense-1.4.2.29.2.jar                        | None                                     |
> 	| LC    | tinkertoolleveling              | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
> 	| LC    | tombstone                       | 3.5.5                    | tombstone-3.5.5-1.12.jar                             | None                                     |
> 	| LC    | toxicrain                       | 2.0.0                    | ToxicRain-1.12.2-2.0.0.jar                           | None                                     |
> 	| LC    | tropicraft                      | 7.1.9.115                | tropicraft-MC1.12.2-7.1.9.115.jar                    | None                                     |
> 	| LC    | tumbleweed                      | 1.11-0.4.5               | tumbleweed-1.11-0.4.5.jar                            | None                                     |
> 	| LC    | universalbestiary               | 1.1.0                    | universalbestiary-1.12.2-1.1.0.jar                   | None                                     |
> 	| LC    | vc                              | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                          | None                                     |
> 	| LC    | waystones                       | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                          | None                                     |
> 	| LC    | zombieawareness                 | 1.12.1-1.11.16           | zombieawareness-1.12.1-1.11.16.jar                   | None                                     |
> 	| LC    | phosphor-lighting               | 1.12.2-0.2.4             | phosphor-1.12.2-0.2.4+build46.jar                    | f0387d288626cc2d937daa504e74af570c52a2f1 |
> 	| LC    | orelib                          | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
> 	| LC    | dsurround                       | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
> 	| LC    | thebetweenlands                 | 3.4.9                    | TheBetweenlands-3.4.9-universal.jar                  | 38067d6878811efb38b6a045521cfd80b9b60b38 |
> 	| LC    | midnight                        | 0.3.5                    | themidnight-0.3.5.jar                                | None                                     |
> 	| LC    | armoryexpansion-conarm          | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
> 	| LC    | librarianliblate                | 4.19.2                   | librarianlib-1.12.2-4.19.2-release.jar               | None                                     |
> 	| LC    | mysticallib                     | 1.12.2-1.3.3             | mysticallib-1.12.2-1.3.3.jar                         | None                                     |
> 
> 	Loaded coremods (and transformers): 
> TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
>   thebetweenlands.core.TheBetweenlandsClassTransformer
> HCASM (HammerCore-1.12.2-2.0.4.7.jar)
>   com.zeitheron.hammercore.asm.HammerCoreTransformer
> midnight (themidnight-0.3.5.jar)
>   com.mushroom.midnight.core.transformer.MidnightClassTransformer
> AstralCore (astralsorcery-1.12.2-1.10.20.jar)
>   
> CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
>   team.chisel.ctm.client.asm.CTMTransformer
> ForgelinPlugin (Forgelin-1.8.3.jar)
>   
> Plugin (NotEnoughIDs-1.5.4.4.jar)
>   ru.fewizz.neid.asm.Transformer
> llibrary (llibrary-core-1.0.11-1.12.2.jar)
>   net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
>   net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
> IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
>   blusunrize.immersiveengineering.common.asm.IEClassTransformer
> LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
>   com.teamwizardry.librarianlib.asm.LibLibTransformer
> AALoadingPlugin (arcanearchives-0.2.0.6.jar)
>   
> PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
>   
> SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
>   sereneseasons.asm.transformer.EntityRendererTransformer
>   sereneseasons.asm.transformer.WorldTransformer
> IvToolkit (IvToolkit-1.3.3-1.12.jar)
>   
> DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
>   org.orecruncher.dsurround.asm.Transformer
> FarseekCoreMod (Farseek-1.12-2.3.2.jar)
>   farseek.core.FarseekClassTransformer
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.60' Renderer: 'GeForce RTX 2080/PCIe/SSE2'
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerWorld (Enabled/Not Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerGadgets (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)
> 		- chiselIntegration (Enabled/Not Forced)
> 
> 	Pulsar/natura loaded Pulses: 
> 		- NaturaCommons (Enabled/Forced)
> 		- NaturaOverworld (Enabled/Not Forced)
> 		- NaturaNether (Enabled/Not Forced)
> 		- NaturaDecorative (Enabled/Not Forced)
> 		- NaturaTools (Enabled/Not Forced)
> 		- NaturaEntities (Enabled/Not Forced)
> 		- NaturaOredict (Enabled/Forced)
> 		- NaturaWorld (Enabled/Not Forced)
> 
> 	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
> OreDictionary Info: Registered 528 names; 560 stacks.
> Pastebin Connection: Okay.
> Dependent Mods:
>     -Botanic Additions (botanicadds) @3r
>     -Improvable Skills (improvableskills) @3.6.3r
> 
> 	OptiFine Version: OptiFine_1.12.2_HD_U_E3
> 	OptiFine Build: 20181210-121000
> 	Render Distance Chunks: 10
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.6.0 NVIDIA 431.60
> 	OpenGlRenderer: GeForce RTX 2080/PCIe/SSE2
> 	OpenGlVendor: NVIDIA Corporation
> 	CpuCount: 16
> ```

**Comment by Syndaryl** [comment]
This issue seems to be resolved in 1.4.2.29.3 (for me anyways)
