### ISSUE TITLE
Crash when interacting with tool forge

### ISSUE THREAD

**Issue by Boter316** [Lance5057/Tinkers-Defense#31]
doing anything with the tool forge, repairing, modifying causes a crash, crash report here

---- Minecraft Crash Report ----
// There are four lights!

Time: 8/13/16 3:11 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at lance5057.tDefense.core.tools.modifiers.Thaumcraft.modifierRepairVis.matches(modifierRepairVis.java:32)
	at tconstruct.library.crafting.ModifyBuilder.modifyItem(ModifyBuilder.java:25)
	at tconstruct.tools.logic.ToolForgeLogic.buildTool(ToolForgeLogic.java:49)
	at tconstruct.tools.logic.ToolStationLogic.func_70296_d(ToolStationLogic.java:65)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at cofh.lib.util.helpers.InventoryHelper.mergeItemStack(InventoryHelper.java:360)
	at net.minecraft.inventory.Container.func_75135_a(SourceFile)
	at tconstruct.tools.inventory.ToolStationContainer.func_82846_b(ToolStationContainer.java:119)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(Unknown Source)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at tconstruct.tools.gui.ToolStationGui.func_73864_a(ToolStationGui.java:69)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at lance5057.tDefense.core.tools.modifiers.Thaumcraft.modifierRepairVis.matches(modifierRepairVis.java:32)
	at tconstruct.library.crafting.ModifyBuilder.modifyItem(ModifyBuilder.java:25)
	at tconstruct.tools.logic.ToolForgeLogic.buildTool(ToolForgeLogic.java:49)
	at tconstruct.tools.logic.ToolStationLogic.func_70296_d(ToolStationLogic.java:65)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at cofh.lib.util.helpers.InventoryHelper.mergeItemStack(InventoryHelper.java:360)
	at net.minecraft.inventory.Container.func_75135_a(SourceFile)
	at tconstruct.tools.inventory.ToolStationContainer.func_82846_b(ToolStationContainer.java:119)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(Unknown Source)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at tconstruct.tools.gui.ToolStationGui.func_73864_a(ToolStationGui.java:69)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: tconstruct.tools.gui.ToolForgeGui

now you don't crash when you open the menu, only when you try to do something with it

**Comment by Lance5057** [comment]
This was probably the same as #21, but I don't know what you had installed. Either way it should be fixed.
