### ISSUE TITLE
Issue with Kcauldron/Thermos

### ISSUE THREAD

**Issue by Boter316** [Lance5057/Tinkers-Defense#39]
I tried to boot it up with KCauldron and got this

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 11/28/16 11:54 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.command.CommandHandler.registerCommand(CommandHandler.java:157)
	at net.minecraft.command.CommandHandler.func_71560_a(CommandHandler.java:143)
	at lance5057.tDefense.TinkersDefense.preInit(TinkersDefense.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1614.201 Official
	Plugins: ~~ERROR~~ NullPointerException: null
	Disabled Plugins: ~~ERROR~~ NullPointerException: null
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3322177776 bytes (3168 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.201.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.201.jar) 
	UCH	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCH	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCE	tinkersdefense{1.3.7} [Tinkers' Defense] (tinkersdefense-1.3.7.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

I cannot do anything more from my end but I figured I'd let you know

**Comment by Boter316** [comment]
and this is with thermos

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/28/16 12:02 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.command.CommandHandler.registerCommand(CommandHandler.java:157)
	at net.minecraft.command.CommandHandler.func_71560_a(CommandHandler.java:143)
	at lance5057.tDefense.TinkersDefense.preInit(TinkersDefense.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58
	Plugins: ~~ERROR~~ NullPointerException: null
	Disabled Plugins: ~~ERROR~~ NullPointerException: null
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3162509232 bytes (3016 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (craftbukkit.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (craftbukkit.jar) 
	UCH	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCH	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCE	tinkersdefense{1.3.7} [Tinkers' Defense] (tinkersdefense-1.3.7.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by lilmoefow** [comment]
Bukkit/Sponge are not the same thing, to start.   For Thermos use version 57 not 58.  And I have never used TinkersDefense1.3.7 on a server with Thermos, but I do know that 1.2.1 works on Thermos servers.

**Comment by Boter316** [comment]
Vanilla Forge with Sponge as PluginAPI does exactly the same, but will test with Termos 57

**Comment by lilmoefow** [comment]
Sponge is not available for 1.7.10 so I dont know what you are talking about dude.

**Comment by lilmoefow** [comment]
Sponge is not availbable for 1.7.10  only 1.8.9+ so, no it doesnt "do the exact same thing" .   Both those "logs" you sent, one shows you have KCauldron loaded up and the other shows you have Thermos loaded up.

KCauldron Version: pw.prok:KCauldron:1.7.10-1614.201 Officia

Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58

Neither of those are sponge.

**Comment by Boter316** [comment]
tbh, me neither, I'm reporting someone else's error, I dont' care much for plugins and whatnot but they do, and I feel like this may be important for modpacks in the future

**Comment by lilmoefow** [comment]
I feel like the mod dev has moved on to 1.9+ so I am afraid this probably won't get fixed.   If you are able to, ask the person to try downgrading the version of tinkers defence to 1.2.1 like I suggested.  And if they are having problems further, I'll see if I can try to get something working when I get home from work
