### ISSUE TITLE
Conflict with TAIGA

### ISSUE THREAD

**Issue by DeadVoid118** [Lance5057/Tinkers-Defense#74]
The mod seems to not work with the other Tinkers' Construct add-on, [TAIGA](https://minecraft.curseforge.com/projects/taiga-tinkers-alloying-addon). Granted, I do have other mods running alongside it, but disabling TAIGA makes the game work perfectly. With it enabled, the game simply crashes before getting to the menu. This was the error code I got: 
```
--- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 9/7/18 6:23 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Compendium (tinkerscompendium)
Caused by: java.lang.NullPointerException
	at lance5057.tDefense.core.materials.TDMaterials.init(TDMaterials.java:927)
	at lance5057.tDefense.TinkersDefense.init(TinkersDefense.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1410327528 bytes (1344 MB) / 3054501888 bytes (2913 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 Optifine OptiFine_1.12.2_HD_U_E2 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                  | Source                                          | Signature                                |
	|:----- |:------------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft                | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHI  | mcp                      | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHI  | FML                      | 8.0.99.99                | forge-1.12.2-14.23.4.2759-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                    | 14.23.4.2759             | forge-1.12.2-14.23.4.2759-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | ivtoolkit                | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCHI  | codechickenlib           | 3.2.1.351                | CodeChickenLib-1.12.2-3.2.1.351-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI  | ancientwarfare           | 1.12.2-2.6.1.349         | ancientwarfare-1.12.2-2.6.1.349.jar             | None                                     |
	| UCHI  | ancientwarfareautomation | 1.12.2-2.6.1.349         | ancientwarfare-1.12.2-2.6.1.349.jar             | None                                     |
	| UCHI  | ancientwarfarenpc        | 1.12.2-2.6.1.349         | ancientwarfare-1.12.2-2.6.1.349.jar             | None                                     |
	| UCHI  | ancientwarfarestructure  | 1.12.2-2.6.1.349         | ancientwarfare-1.12.2-2.6.1.349.jar             | None                                     |
	| UCHI  | ancientwarfarevehicle    | 1.12.2-2.6.1.349         | ancientwarfare-1.12.2-2.6.1.349.jar             | None                                     |
	| UCHI  | antiqueatlas             | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHI  | antiqueatlasoverlay      | 1.2                      | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHI  | examplemod               | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHI  | jei                      | 4.11.0.212               | jei_1.12.2-4.11.0.212.jar                       | None                                     |
	| UCHI  | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHI  | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHI  | betterbuilderswands      | 0.12.0                   | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar | None                                     |
	| UCHI  | biomesoplenty            | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar   | None                                     |
	| UCHI  | clumps                   | 3.1.1                    | Clumps-3.1.1.jar                                | None                                     |
	| UCHI  | mantle                   | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHI  | twilightforest           | 3.8.654                  | twilightforest-1.12.2-3.8.654-universal.jar     | None                                     |
	| UCHI  | tconstruct               | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCHI  | conarm                   | 1.1.1                    | conarm-1.12.2-1.1.1.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI  | cyclopscore              | 0.11.9                   | CyclopsCore-1.12.2-0.11.9.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHI  | dldungeonsjdg            | 1.11.1                   | DoomlikeDungeons-1.11.1-MC1.12.2.jar            | None                                     |
	| UCHI  | erebus                   | 1.0.22                   | Erebus-1.0.22.jar                               | None                                     |
	| UCHI  | everlastingabilities     | 1.3.17                   | EverlastingAbilities-1.12.2-1.3.17.jar          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHI  | fastfurnace              | 1.1.0                    | FastFurnace-1.12.2-1.1.0.jar                    | None                                     |
	| UCHI  | fastleafdecay            | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UCHI  | fastbench                | 1.5.3                    | FastWorkbench-1.12.2-1.5.3.jar                  | None                                     |
	| UCHI  | ferdinandsflowers        | 1.10.1b                  | Ferdinand's+Flowers-1.10.1b-1.12.jar            | None                                     |
	| UCHI  | grimoireofgaia           | 1.6.0-beta5              | GrimoireOfGaia3-1.12.2-1.6.0-beta5.jar          | None                                     |
	| UCHI  | ichunutil                | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHI  | hats                     | 7.0.0                    | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCHI  | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHI  | journeymap               | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHI  | limelib                  | 1.7.12                   | limelib-1.12.2-1.7.12.jar                       | None                                     |
	| UCHI  | lootbags                 | 2.5.7                    | LootBags-1.12.2-2.5.7.jar                       | None                                     |
	| UCHI  | lostcities               | 2.0.10                   | lostcities-1.12-2.0.10.jar                      | None                                     |
	| UCHI  | lostsouls                | 1.1.4                    | lostsouls-1.12-1.1.4.jar                        | None                                     |
	| UCHI  | mousetweaks              | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCHI  | oreexcavation            | 1.4.129                  | OreExcavation-1.4.129.jar                       | None                                     |
	| UCHI  | playerstorage            | 1.3.6                    | playerstorage-1.12.2-1.3.6.jar                  | None                                     |
	| UCHI  | reccomplex               | 1.4.7                    | RecurrentComplex-1.4.7.jar                      | None                                     |
	| UCHI  | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHI  | silentlib                | 3.0.1                    | SilentLib-1.12.2-3.0.1-145.jar                  | None                                     |
	| UCHI  | scalinghealth            | 1.3.26                   | ScalingHealth-1.12.2-1.3.26-127.jar             | None                                     |
	| UCHI  | soulshardsrespawn        | 1.12.2-1.0.6-8           | SoulShardsRespawn-1.12.2-1.0.6-8.jar            | None                                     |
	| UCHI  | stg                      | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                            | None                                     |
	| UCHI  | taiga                    | 1.3.2                    | taiga-1.12.2-1.3.2.jar                          | None                                     |
	| UCHI  | tinkersaddons            | 1.0.7                    | Tinkers'+Addons-1.12.1-1.0.7.jar                | None                                     |
	| UCHEE | tinkerscompendium        | 1.4.2.18a                | tinkersdefense-1.4.2.18a.jar                    | None                                     |
	| UCH   | tinkersjei               | 1.0                      | tinkersjei-1.0.jar                              | None                                     |
	| UCH   | tinkertoolleveling       | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar             | None                                     |
	| UCH   | torchbandolier           | 0.1.1                    | TorchBandolier-1.12.2-0.1.1-4.jar               | None                                     |
	| UCH   | wawla                    | 2.5.260                  | Wawla-1.12.2-2.5.260.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 620/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GT 620/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by NickelHub** [comment]
I got the same crash.
[crash-2018-09-21_14.59.02-client.txt](https://github.com/Lance5057/Tinkers-Defense/files/2405437/crash-2018-09-21_14.59.02-client.txt)

**Comment by Lance5057** [comment]
Add Nihilite to the material blacklist, or stop using TIAGA because it's been abandon by its creator.
